export const locations = [
  {
    id: 1,
    name: "East Midlands",
    slug: "east-midlands",
    areas: [
      { id: 1, name: "Derbyshire", slug: "derbyshire" },
      { id: 2, name: "Leicestershire", slug: "leicestershire" },
      { id: 3, name: "Northamptonshire", slug: "northamptonshire" },
      { id: 4, name: "Nottinghamshire", slug: "nottinghamshire" },
      { id: 5, name: "Rutland", slug: "rutland" },
    ],
  },
  {
    id: 2,
    name: "East of England",
    slug: "east-of-england",
    areas: [
      { id: 1, name: "Bedfordshire", slug: "bedfordshire" },
      { id: 2, name: "Cambridgeshire", slug: "cambridgeshire" },
      { id: 3, name: "Essex", slug: "essex" },
      { id: 4, name: "Hertfordshire", slug: "hertfordshire" },
      { id: 5, name: "Norfolk", slug: "norfolk" },
      { id: 6, name: "Suffolk", slug: "suffolk" },
    ],
  },
  {
    id: 3,
    name: "London",
    slug: "london",
    areas: [
      { id: 1, name: "Central London", slug: "central-london" },
      { id: 2, name: "East London", slug: "east-london" },
      { id: 3, name: "North London", slug: "north-london" },
      { id: 4, name: "South London", slug: "south-london" },
      { id: 5, name: "West London", slug: "west-london" },
    ],
  },
  {
    id: 4,
    name: "North East England",
    slug: "north-east-england",
    areas: [
      { id: 1, name: "County Durham", slug: "county-durham" },
      { id: 2, name: "Northumberland", slug: "northumberland" },
      { id: 3, name: "Tyne and Wear", slug: "tyne-and-wear" },
    ],
  },
  {
    id: 5,
    name: "North West England",
    slug: "north-west-england",
    areas: [
      { id: 1, name: "Cheshire", slug: "cheshire" },
      { id: 2, name: "Cumbria", slug: "cumbria" },
      { id: 3, name: "Greater Manchester", slug: "greater-manchester" },
      { id: 4, name: "Lancashire", slug: "lancashire" },
      { id: 5, name: "Merseyside", slug: "merseyside" },
    ],
  },
  {
    id: 6,
    name: "South East England",
    slug: "south-east-england",
    areas: [
      { id: 1, name: "Berkshire", slug: "berkshire" },
      { id: 2, name: "Buckinghamshire", slug: "buckinghamshire" },
      { id: 3, name: "East Sussex", slug: "east-sussex" },
      { id: 4, name: "Hampshire", slug: "hampshire" },
      { id: 5, name: "Isle of Wight", slug: "isle-of-wight" },
      { id: 6, name: "Kent", slug: "kent" },
      { id: 7, name: "Oxfordshire", slug: "oxfordshire" },
      { id: 8, name: "Surrey", slug: "surrey" },
      { id: 9, name: "West Sussex", slug: "west-sussex" },
    ],
  },
  {
    id: 7,
    name: "South West England",
    slug: "south-west-england",
    areas: [
      { id: 1, name: "Bristol", slug: "bristol" },
      { id: 2, name: "Cornwall", slug: "cornwall" },
      { id: 3, name: "Devon", slug: "devon" },
      { id: 4, name: "Dorset", slug: "dorset" },
      { id: 5, name: "Gloucestershire", slug: "gloucestershire" },
      { id: 6, name: "Isles of Scilly", slug: "isles-of-scilly" },
      { id: 7, name: "Somerset", slug: "somerset" },
      { id: 8, name: "Wiltshire", slug: "wiltshire" },
    ],
  },
  {
    id: 8,
    name: "West Midlands",
    slug: "west-midlands",
    areas: [
      { id: 1, name: "Herefordshire", slug: "herefordshire" },
      { id: 2, name: "Shropshire", slug: "shropshire" },
      { id: 3, name: "Staffordshire", slug: "staffordshire" },
      { id: 4, name: "Warwickshire", slug: "warwickshire" },
      { id: 5, name: "West Midlands", slug: "west-midlands-region" },
      { id: 6, name: "Worcestershire", slug: "worcestershire" },
    ],
  },
  {
    id: 9,
    name: "Yorkshire and the Humber",
    slug: "yorkshire-and-the-humber",
    areas: [
      {
        id: 1,
        name: "East Riding of Yorkshire",
        slug: "east-riding-of-yorkshire",
      },
      { id: 2, name: "Lincolnshire", slug: "lincolnshire" },
      { id: 3, name: "North Yorkshire", slug: "north-yorkshire" },
      { id: 4, name: "South Yorkshire", slug: "south-yorkshire" },
      { id: 5, name: "West Yorkshire", slug: "west-yorkshire" },
    ],
  },
  {
    id: 10,
    name: "Scotland",
    slug: "scotland",
    areas: [
      { id: 1, name: "Aberdeen City", slug: "aberdeen-city" },
      { id: 2, name: "Aberdeenshire", slug: "aberdeenshire" },
      { id: 3, name: "Angus", slug: "angus" },
      { id: 4, name: "Argyll and Bute", slug: "argyll-and-bute" },
      { id: 5, name: "Clackmannanshire", slug: "clackmannanshire" },
      { id: 6, name: "Dumfries and Galloway", slug: "dumfries-and-galloway" },
      { id: 7, name: "Dundee City", slug: "dundee-city" },
      { id: 8, name: "East Ayrshire", slug: "east-ayrshire" },
      { id: 9, name: "East Dunbartonshire", slug: "east-dunbartonshire" },
      { id: 10, name: "East Lothian", slug: "east-lothian" },
      { id: 11, name: "East Renfrewshire", slug: "east-renfrewshire" },
      { id: 12, name: "Edinburgh", slug: "edinburgh" },
      { id: 13, name: "Falkirk", slug: "falkirk" },
      { id: 14, name: "Fife", slug: "fife" },
      { id: 15, name: "Glasgow City", slug: "glasgow-city" },
      { id: 16, name: "Highland", slug: "highland" },
      { id: 17, name: "Inverclyde", slug: "inverclyde" },
      { id: 18, name: "Midlothian", slug: "midlothian" },
      { id: 19, name: "Moray", slug: "moray" },
      { id: 20, name: "Na h-Eileanan Siar", slug: "na-h-eileanan-siar" },
      { id: 21, name: "North Ayrshire", slug: "north-ayrshire" },
      { id: 22, name: "North Lanarkshire", slug: "north-lanarkshire" },
      { id: 23, name: "Orkney Islands", slug: "orkney-islands" },
      { id: 24, name: "Perth and Kinross", slug: "perth-and-kinross" },
      { id: 25, name: "Renfrewshire", slug: "renfrewshire" },
      { id: 26, name: "Scottish Borders", slug: "scottish-borders" },
      { id: 27, name: "Shetland Islands", slug: "shetland-islands" },
      { id: 28, name: "South Ayrshire", slug: "south-ayrshire" },
      { id: 29, name: "South Lanarkshire", slug: "south-lanarkshire" },
      { id: 30, name: "Stirling", slug: "stirling" },
      { id: 31, name: "West Dunbartonshire", slug: "west-dunbartonshire" },
      { id: 32, name: "West Lothian", slug: "west-lothian" },
    ],
  },
  {
    id: 11,
    name: "Wales",
    slug: "wales",
    areas: [
      { id: 1, name: "Blaenau Gwent", slug: "blaenau-gwent" },
      { id: 2, name: "Bridgend County", slug: "bridgend-county" },
      { id: 3, name: "Caerphilly County", slug: "caerphilly-county" },
      { id: 4, name: "Cardiff", slug: "cardiff" },
      { id: 5, name: "Carmarthenshire", slug: "carmarthenshire" },
      { id: 6, name: "Ceredigion", slug: "ceredigion" },
      {
        id: 7,
        name: "City and County of Swansea",
        slug: "city-and-county-of-swansea",
      },
      { id: 8, name: "Conwy County Borough", slug: "conwy-county-borough" },
      { id: 9, name: "Denbighshire", slug: "denbighshire" },
      { id: 10, name: "Flintshire", slug: "flintshire" },
      { id: 11, name: "Gwynedd", slug: "gwynedd" },
      { id: 12, name: "Isle of Anglesey", slug: "isle-of-anglesey" },
      {
        id: 13,
        name: "Merthyr Tydfil County Borough",
        slug: "merthyr-tydfil-county-borough",
      },
      { id: 14, name: "Monmouthshire", slug: "monmouthshire" },
      { id: 15, name: "Neath Port Talbot", slug: "neath-port-talbot" },
      { id: 16, name: "Newport", slug: "newport" },
      { id: 17, name: "Pembrokeshire", slug: "pembrokeshire" },
      { id: 18, name: "Powys", slug: "powys" },
      { id: 19, name: "Rhondda Cynon Taf", slug: "rhondda-cynon-taf" },
      { id: 20, name: "Torfaen", slug: "torfaen" },
      { id: 21, name: "Vale of Glamorgan", slug: "vale-of-glamorgan" },
      { id: 22, name: "Wrexham", slug: "wrexham" },
    ],
  },
  {
    id: 12,
    name: "Northern Ireland",
    slug: "northern-ireland",
    areas: [
      {
        id: 1,
        name: "Antrim and Newtownabbey",
        slug: "antrim-and-newtownabbey",
      },
      { id: 2, name: "Ards and North Down", slug: "ards-and-north-down" },
      {
        id: 3,
        name: "Armagh City, Banbridge and Craigavon",
        slug: "armagh-city-banbridge-and-craigavon",
      },
      { id: 4, name: "Belfast", slug: "belfast" },
      {
        id: 5,
        name: "Causeway Coast and Glens",
        slug: "causeway-coast-and-glens",
      },
      {
        id: 6,
        name: "Derry City and Strabane",
        slug: "derry-city-and-strabane",
      },
      { id: 7, name: "Fermanagh and Omagh", slug: "fermanagh-and-omagh" },
      {
        id: 8,
        name: "Lisburn and Castlereagh",
        slug: "lisburn-and-castlereagh",
      },
      { id: 9, name: "Mid and East Antrim", slug: "mid-and-east-antrim" },
      { id: 10, name: "Mid Ulster", slug: "mid-ulster" },
      { id: 11, name: "Newry, Mourne and Down", slug: "newry-mourne-and-down" },
    ],
  },
];
